# Smoke testing client samples on Polarion instance

name: Smoke testing (Polarion)

on:
#  push:
#    branches: [main]
  schedule:
    - cron: "11 04 * * 4" # catch SNAPSHOT breaking changes
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-smoke-polarion
  cancel-in-progress: ${{ github.event_name == 'pull_request' && !contains(github.event.pull_request.labels.*.name, 'ci:full') }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: 'temurin'
      - name: Build Lyo Client samples
        run: |
          mvn -B clean verify --file lyo-client-samples/pom.xml
      - name: E2E client samples tests on Polarion
        run: ./bin/test-polarion.sh
        env:
          POLARION_PAT: ${{ secrets.POLARION_PAT }}
          POLARION_ROOT_SERVICES: ${{ vars.POLARION_ROOT_SERVICES }}
          POLARION_PROJECT: ${{ vars.POLARION_PROJECT }}
